sudo: required

language: ruby

services:
  - docker

before_script:
  - pushd .. > /dev/null
  - git clone https://github.com/viaq/docker-elasticsearch
  - git clone https://github.com/viaq/docker-fluentd
  - popd > /dev/null

script:
  - bash ./openshift-test.sh

notifications:
  irc: "chat.freenode.net#viaq"
